version: '{branch}-{build}'
build: off
environment:
  global:
    TWINE_USERNAME: ionel
  matrix:
    - TOXENV: check
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
    - TOXENV: py27-pure-cover,codecov
      TOXPYTHON: C:\Python27\python.exe
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
    - TOXENV: py27-pure-cover,codecov
      TOXPYTHON: C:\Python27-x64\python.exe
      PYTHON_HOME: C:\Python27-x64
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '64'
      WINDOWS_SDK_VERSION: v7.0
    - TOXENV: py27-pure-nocov
      TOXPYTHON: C:\Python27\python.exe
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
    - TOXENV: py27-pure-nocov
      TOXPYTHON: C:\Python27-x64\python.exe
      PYTHON_HOME: C:\Python27-x64
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '64'
      WINDOWS_SDK_VERSION: v7.0
    - TOXENV: py27-cython-cover,codecov
      TOXPYTHON: C:\Python27\python.exe
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
    - TOXENV: py27-cython-cover,codecov
      TOXPYTHON: C:\Python27-x64\python.exe
      PYTHON_HOME: C:\Python27-x64
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '64'
      WINDOWS_SDK_VERSION: v7.0
    - TOXENV: py27-cython-nocov
      TOXPYTHON: C:\Python27\python.exe
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
      WHEEL_PATH: .tox/dist
    - TOXENV: py27-cython-nocov
      TOXPYTHON: C:\Python27-x64\python.exe
      PYTHON_HOME: C:\Python27-x64
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '64'
      WHEEL_PATH: .tox/dist
      WINDOWS_SDK_VERSION: v7.0
    - TOXENV: py35-pure-cover,codecov
      TOXPYTHON: C:\Python35\python.exe
      PYTHON_HOME: C:\Python35
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'
    - TOXENV: py35-pure-cover,codecov
      TOXPYTHON: C:\Python35-x64\python.exe
      PYTHON_HOME: C:\Python35-x64
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '64'
    - TOXENV: py35-pure-nocov
      TOXPYTHON: C:\Python35\python.exe
      PYTHON_HOME: C:\Python35
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'
    - TOXENV: py35-pure-nocov
      TOXPYTHON: C:\Python35-x64\python.exe
      PYTHON_HOME: C:\Python35-x64
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '64'
    - TOXENV: py35-cython-cover,codecov
      TOXPYTHON: C:\Python35\python.exe
      PYTHON_HOME: C:\Python35
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'
    - TOXENV: py35-cython-cover,codecov
      TOXPYTHON: C:\Python35-x64\python.exe
      PYTHON_HOME: C:\Python35-x64
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '64'
    - TOXENV: py35-cython-nocov
      TOXPYTHON: C:\Python35\python.exe
      PYTHON_HOME: C:\Python35
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'
      WHEEL_PATH: .tox/dist
    - TOXENV: py35-cython-nocov
      TOXPYTHON: C:\Python35-x64\python.exe
      PYTHON_HOME: C:\Python35-x64
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '64'
      WHEEL_PATH: .tox/dist
    - TOXENV: py36-pure-cover,codecov
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
    - TOXENV: py36-pure-cover,codecov
      TOXPYTHON: C:\Python36-x64\python.exe
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'
    - TOXENV: py36-pure-nocov
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
    - TOXENV: py36-pure-nocov
      TOXPYTHON: C:\Python36-x64\python.exe
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'
    - TOXENV: py36-cython-cover,codecov
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
    - TOXENV: py36-cython-cover,codecov
      TOXPYTHON: C:\Python36-x64\python.exe
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'
    - TOXENV: py36-cython-nocov
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
      WHEEL_PATH: .tox/dist
    - TOXENV: py36-cython-nocov
      TOXPYTHON: C:\Python36-x64\python.exe
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'
      WHEEL_PATH: .tox/dist
    - TOXENV: py37-pure-cover,codecov
      TOXPYTHON: C:\Python37\python.exe
      PYTHON_HOME: C:\Python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
    - TOXENV: py37-pure-cover,codecov
      TOXPYTHON: C:\Python37-x64\python.exe
      PYTHON_HOME: C:\Python37-x64
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
    - TOXENV: py37-pure-nocov
      TOXPYTHON: C:\Python37\python.exe
      PYTHON_HOME: C:\Python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
    - TOXENV: py37-pure-nocov
      TOXPYTHON: C:\Python37-x64\python.exe
      PYTHON_HOME: C:\Python37-x64
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
    - TOXENV: py37-cython-cover,codecov
      TOXPYTHON: C:\Python37\python.exe
      PYTHON_HOME: C:\Python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
    - TOXENV: py37-cython-cover,codecov
      TOXPYTHON: C:\Python37-x64\python.exe
      PYTHON_HOME: C:\Python37-x64
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
    - TOXENV: py37-cython-nocov
      TOXPYTHON: C:\Python37\python.exe
      PYTHON_HOME: C:\Python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
      WHEEL_PATH: .tox/dist
    - TOXENV: py37-cython-nocov
      TOXPYTHON: C:\Python37-x64\python.exe
      PYTHON_HOME: C:\Python37-x64
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
      WHEEL_PATH: .tox/dist
    - TOXENV: py38-pure-cover,codecov
      TOXPYTHON: C:\Python38\python.exe
      PYTHON_HOME: C:\Python38
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '32'
    - TOXENV: py38-pure-cover,codecov
      TOXPYTHON: C:\Python38-x64\python.exe
      PYTHON_HOME: C:\Python38-x64
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '64'
    - TOXENV: py38-pure-nocov
      TOXPYTHON: C:\Python38\python.exe
      PYTHON_HOME: C:\Python38
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '32'
    - TOXENV: py38-pure-nocov
      TOXPYTHON: C:\Python38-x64\python.exe
      PYTHON_HOME: C:\Python38-x64
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '64'
    - TOXENV: py38-cython-cover,codecov
      TOXPYTHON: C:\Python38\python.exe
      PYTHON_HOME: C:\Python38
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '32'
    - TOXENV: py38-cython-cover,codecov
      TOXPYTHON: C:\Python38-x64\python.exe
      PYTHON_HOME: C:\Python38-x64
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '64'
    - TOXENV: py38-cython-nocov
      TOXPYTHON: C:\Python38\python.exe
      PYTHON_HOME: C:\Python38
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '32'
      WHEEL_PATH: .tox/dist
    - TOXENV: py38-cython-nocov
      TOXPYTHON: C:\Python38-x64\python.exe
      PYTHON_HOME: C:\Python38-x64
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '64'
      WHEEL_PATH: .tox/dist
init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
  - ps: |
      Set-PSDebug -Trace 1
      if ($Env:TOXENV.StartsWith("py38")) {
        if ($Env:PYTHON_ARCH -eq "64") {
          iex "choco install python3 --version=3.8 --no-progress --params /InstallDir:$Env:PYTHON_HOME"
        } else {
          iex "choco install python3 --version=3.8 --no-progress --params /InstallDir:$Env:PYTHON_HOME --x86"
        }
      }
  - '%PYTHON_HOME%\python -mpip install --progress-bar=off twine tox-wheel -rci/requirements.txt'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\easy_install --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
test_script:
  - ps: |
      Set-PSDebug -Trace 1
      if ($Env:WHEEL_PATH) {
        cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd $Env:PYTHON_HOME\Scripts\tox --wheel
        if ($LastExitCode -eq 0) {
          $ErrorActionPreference = "Stop"
          iex "$Env:PYTHON_HOME\Scripts\twine check $Env:WHEEL_PATH/*.whl"
          iex "$Env:PYTHON_HOME\Scripts\twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing $Env:WHEEL_PATH/*.whl"
        }
      } else {
        cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd $Env:PYTHON_HOME\Scripts\tox
      }
      if ($LastExitCode -ne 0) {
        Get-ChildItem Env:
        Get-Content .tox\*\log\*
      }

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
