version: '{branch}-{build}'
build: off
environment:
  global:
    TWINE_PASSWORD:
      secure: fDwCnDhQiptm9a4ZcFpgyQ==
    TWINE_USERNAME: ionel
  matrix:
    - TOXENV: check
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
    - TOXENV: 'py27-pure-cover,codecov'
      TOXPYTHON: C:\Python27\python.exe
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
    - TOXENV: 'py27-pure-cover,codecov'
      TOXPYTHON: C:\Python27-x64\python.exe
      WINDOWS_SDK_VERSION: v7.0
      PYTHON_HOME: C:\Python27-x64
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '64'
    - TOXENV: 'py27-pure-nocov'
      TOXPYTHON: C:\Python27\python.exe
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
    - TOXENV: 'py27-pure-nocov'
      TOXPYTHON: C:\Python27-x64\python.exe
      WINDOWS_SDK_VERSION: v7.0
      PYTHON_HOME: C:\Python27-x64
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '64'
    - TOXENV: 'py27-cython-cover,codecov'
      TOXPYTHON: C:\Python27\python.exe
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
    - TOXENV: 'py27-cython-cover,codecov'
      TOXPYTHON: C:\Python27-x64\python.exe
      WINDOWS_SDK_VERSION: v7.0
      PYTHON_HOME: C:\Python27-x64
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '64'
    - TOXENV: 'py27-cython-nocov'
      TOXPYTHON: C:\Python27\python.exe
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
      WHEEL_PATH: .tox/dist
    - TOXENV: 'py27-cython-nocov'
      TOXPYTHON: C:\Python27-x64\python.exe
      WINDOWS_SDK_VERSION: v7.0
      PYTHON_HOME: C:\Python27-x64
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '64'
      WHEEL_PATH: .tox/dist
    - TOXENV: 'py35-pure-cover,codecov'
      TOXPYTHON: C:\Python35\python.exe
      PYTHON_HOME: C:\Python35
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'
    - TOXENV: 'py35-pure-cover,codecov'
      TOXPYTHON: C:\Python35-x64\python.exe
      PYTHON_HOME: C:\Python35-x64
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '64'
    - TOXENV: 'py35-pure-nocov'
      TOXPYTHON: C:\Python35\python.exe
      PYTHON_HOME: C:\Python35
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'
    - TOXENV: 'py35-pure-nocov'
      TOXPYTHON: C:\Python35-x64\python.exe
      PYTHON_HOME: C:\Python35-x64
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '64'
    - TOXENV: 'py35-cython-cover,codecov'
      TOXPYTHON: C:\Python35\python.exe
      PYTHON_HOME: C:\Python35
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'
    - TOXENV: 'py35-cython-cover,codecov'
      TOXPYTHON: C:\Python35-x64\python.exe
      PYTHON_HOME: C:\Python35-x64
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '64'
    - TOXENV: 'py35-cython-nocov'
      TOXPYTHON: C:\Python35\python.exe
      PYTHON_HOME: C:\Python35
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'
      WHEEL_PATH: .tox/dist
    - TOXENV: 'py35-cython-nocov'
      TOXPYTHON: C:\Python35-x64\python.exe
      PYTHON_HOME: C:\Python35-x64
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '64'
      WHEEL_PATH: .tox/dist
    - TOXENV: 'py36-pure-cover,codecov'
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
    - TOXENV: 'py36-pure-cover,codecov'
      TOXPYTHON: C:\Python36-x64\python.exe
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'
    - TOXENV: 'py36-pure-nocov'
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
    - TOXENV: 'py36-pure-nocov'
      TOXPYTHON: C:\Python36-x64\python.exe
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'
    - TOXENV: 'py36-cython-cover,codecov'
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
    - TOXENV: 'py36-cython-cover,codecov'
      TOXPYTHON: C:\Python36-x64\python.exe
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'
    - TOXENV: 'py36-cython-nocov'
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
      WHEEL_PATH: .tox/dist
    - TOXENV: 'py36-cython-nocov'
      TOXPYTHON: C:\Python36-x64\python.exe
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'
      WHEEL_PATH: .tox/dist
    - TOXENV: 'py37-pure-cover,codecov'
      TOXPYTHON: C:\Python37\python.exe
      PYTHON_HOME: C:\Python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
    - TOXENV: 'py37-pure-cover,codecov'
      TOXPYTHON: C:\Python37-x64\python.exe
      PYTHON_HOME: C:\Python37-x64
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
    - TOXENV: 'py37-pure-nocov'
      TOXPYTHON: C:\Python37\python.exe
      PYTHON_HOME: C:\Python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
    - TOXENV: 'py37-pure-nocov'
      TOXPYTHON: C:\Python37-x64\python.exe
      PYTHON_HOME: C:\Python37-x64
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
    - TOXENV: 'py37-cython-cover,codecov'
      TOXPYTHON: C:\Python37\python.exe
      PYTHON_HOME: C:\Python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
    - TOXENV: 'py37-cython-cover,codecov'
      TOXPYTHON: C:\Python37-x64\python.exe
      PYTHON_HOME: C:\Python37-x64
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
    - TOXENV: 'py37-cython-nocov'
      TOXPYTHON: C:\Python37\python.exe
      PYTHON_HOME: C:\Python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
      WHEEL_PATH: .tox/dist
    - TOXENV: 'py37-cython-nocov'
      TOXPYTHON: C:\Python37-x64\python.exe
      PYTHON_HOME: C:\Python37-x64
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
      WHEEL_PATH: .tox/dist
init:
  - ps: Write-Output $Env:TOXENV
  - ps: Get-ChildItem C:\Python*
install:
  - python -u ci\appveyor-bootstrap.py
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\easy_install --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
test_script:
  - ps: |
      Set-PSDebug -Trace 1
      if ($Env:WHEEL_PATH) {
        cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd $Env:PYTHON_HOME\Scripts\tox --wheel
        if ($LastExitCode -eq 0) {
          $ErrorActionPreference = "Stop"
          iex "$Env:PYTHON_HOME\Scripts\twine check $Env:WHEEL_PATH/*.whl"
          iex "$Env:PYTHON_HOME\Scripts\twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing $Env:WHEEL_PATH/*.whl"
        }
      } else {
        cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd $Env:PYTHON_HOME\Scripts\tox
      }
      if ($LastExitCode -ne 0) {
        Get-ChildItem Env:
        Get-Content .tox\*\log\*
      }

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
