name: build
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    name: {{ '${{ matrix.name }}' }}
    runs-on: {{ '${{ matrix.os }}' }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'check'
            python: '3.13'
            toxpython: 'python3.13'
            tox_env: 'check'
            os: 'ubuntu-latest'
          - name: 'docs'
            python: '3.13'
            toxpython: 'python3.13'
            tox_env: 'docs'
            os: 'ubuntu-latest'
{% for env in tox_environments %}
{% set prefix = env.split('-')[0] -%}
{% set freethreaded = prefix.endswith('t') %}
{% if prefix.startswith('pypy') %}
{% set python %}pypy-{{ prefix[4] }}.{{ prefix[5:] }}{% endset %}
{% set cpython %}pp{{ prefix[4:5] }}{% endset %}
{% else %}
{% set python %}{{ prefix[2] }}.{{ prefix[3:].rstrip('t') }}{% endset %}
{% set cpython %}cp{{ prefix[2:] }}{% endset %}
{% endif %}
{% for os, python_arch, cibw_arch, wheel_arch, include_cover in [
    ['ubuntu', 'x64', 'x86_64', '*manylinux*', True],
    ['ubuntu', 'x64', 'x86_64', '*musllinux*', False],
    ['ubuntu', 'x64', 'aarch64', '*manylinux*', False],
    ['ubuntu', 'x64', 'aarch64', '*musllinux*', False],
    ['windows', 'x64', 'AMD64', '*', True],
    ['windows', 'x86', 'x86', '*', False],
    ['macos', 'arm64', 'arm64', '*', True],
] %}
{% if include_cover or (env.endswith('cython-nocov') and not prefix.startswith('pypy')) %}
{% set wheel_suffix = env.endswith('cython-nocov') and wheel_arch.strip('*') %}
{% set name_suffix = '/' + wheel_suffix if wheel_suffix else '' %}
          - name: '{{ env }} ({{ os }}/{{ cibw_arch }}{{ name_suffix }})'
            artifact: '{{ env.rsplit('-', 1)[0] }}-{{ os }}-{{ cibw_arch }}{{ name_suffix.replace('/', '-') }}'
            python: '{{ python }}'
            python_arch: '{{ python_arch }}{% if freethreaded %}-freethreaded{% endif %}'
            tox_env: '{{ env }}'
{% if 'cover' in env %}
            cover: true
{% endif %}
            cibw_arch: '{{ cibw_arch }}'
{% if env.endswith('cython-nocov') and not prefix.startswith('pypy') %}
            cibw_build: '{{ cpython }}-{{ wheel_arch }}'
            cibw_ft: '{% if freethreaded %}true{% else %}false{% endif %}'
{% else %}
            cibw_build: false
{% endif %}
            os: '{{ os }}-latest'
{% endif %}
{% endfor %}
{% endfor %}
    steps:
    - uses: docker/setup-qemu-action@v3
      if: matrix.cibw_arch == 'aarch64'
      with:
        platforms: arm64
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: {{ '${{ matrix.python }}' }}
        architecture: {{ '${{ matrix.python_arch }}' }}
    - name: install dependencies
      run: |
        python -mpip install --progress-bar=off cibuildwheel -r ci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
        pip list --format=freeze
    - name: install dependencies (gdb)
      if: >
        !matrix.cibw_build && matrix.os == 'ubuntu'
      run: |
        sudo apt-get install gdb
        echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
    - name: cibw build and test
      if: matrix.cibw_build
      run: cibuildwheel
      env:
        CIBW_ARCHS: '{{ '${{ matrix.cibw_arch }}' }}'
        CIBW_BUILD: '{{ '${{ matrix.cibw_build }}' }}'
        CIBW_FREE_THREADED_SUPPORT: '{{ '${{ matrix.cibw_ft }}' }}'
        CIBW_CONTAINER_ENGINE: "docker; create_args: --cap-add=SYS_PTRACE"
        CIBW_ENABLE: cpython-freethreading
        CIBW_BUILD_VERBOSITY: '3'
        CIBW_TEST_REQUIRES: >
          tox
          tox-direct
        CIBW_TEST_COMMAND: >
          cd {project} &&
          tox --skip-pkg-install --direct-yolo -e {{ '${{ matrix.tox_env }}' }} -vv
        CIBW_TEST_COMMAND_WINDOWS: >
          cd /d {project} &&
          tox --skip-pkg-install --direct-yolo -e {{ '${{ matrix.tox_env }}' }} -vv
    - name: regular build and test
      if: >
        !matrix.cibw_build
      run: >
        tox -e {{ '${{ matrix.tox_env }}' }} -vv
    - uses: codecov/codecov-action@v5
      if: matrix.cover
      with:
        verbose: true
        flags: {{ '${{ matrix.tox_env }}' }}
    - name: check wheel
      if: >
        !matrix.cibw_ft && matrix.cibw_build
      run: |
        python -mpip install --progress-bar=off twine
        twine check wheelhouse/*.whl
    - name: upload wheel
      uses: actions/upload-artifact@v4
      if: matrix.cibw_build
      with:
        name: {{ 'wheel-${{ matrix.artifact }}' }}
        path: wheelhouse/*.whl
  finish:
    needs: test
    if: {{ '${{ always() }}' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/upload-artifact/merge@v4
      with:
        name: all-wheels
    - uses: codecov/codecov-action@v5
      with:
        CODECOV_TOKEN: {% raw %}${{ secrets.CODECOV_TOKEN }}{% endraw %}
{{ '' }}
